# Generated by Django 5.1.1 on 2024-10-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.IntegerField(verbose_name='стол')),
                ('date', models.DateField(verbose_name='дата')),
                ('time', models.TimeField(verbose_name='время')),
                ('guests', models.IntegerField(verbose_name='Количество гостей')),
                ('reserve', models.BooleanField(default=False, verbose_name='зарезервирован')),
                ('confirmation_token', models.CharField(blank=True, max_length=32, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Резерв',
                'verbose_name_plural': 'Резервы',
            },
        ),
    ]
